name: TTWOS Checklist

on:
  workflow_dispatch:
    inputs:
      verify_changes:
        description: "Verify all code changes are merged into the main branch"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No
      pass_ci_tests:
        description: "Ensure the main branch passes all CI tests"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No
      version_updated:
        description: "Confirm version number is updated if required"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No
      env_variables:
        description: "Update environment variables if needed"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No
      run_workflow:
        description: "Run workflow dispatch from GitHub Actions"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No

jobs:
  deploy-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Deployment Checklist Table
        id: checklist
        run: |
          # Capture inputs as variables
          VERIFY_CHANGES="${{ github.event.inputs.verify_changes }}"
          PASS_CI_TESTS="${{ github.event.inputs.pass_ci_tests }}"
          VERSION_UPDATED="${{ github.event.inputs.version_updated }}"
          ENV_VARIABLES="${{ github.event.inputs.env_variables }}"
          RUN_WORKFLOW="${{ github.event.inputs.run_workflow }}"

          # Generate the email body with HTML table
          EMAIL_BODY="<h2>Deployment Checklist Summary</h2>
          <table border=\"1\">
            <tr><th>Step</th><th>Description</th><th>Completed</th></tr>
            <tr><td>1</td><td>Verify all code changes are merged</td><td>$VERIFY_CHANGES</td></tr>
            <tr><td>2</td><td>Ensure main branch passes all CI tests</td><td>$PASS_CI_TESTS</td></tr>
            <tr><td>3</td><td>Confirm version number is updated if required</td><td>$VERSION_UPDATED</td></tr>
            <tr><td>4</td><td>Update environment variables if needed</td><td>$ENV_VARIABLES</td></tr>
            <tr><td>5</td><td>Run workflow dispatch from GitHub Actions</td><td>$RUN_WORKFLOW</td></tr>
          </table>"

          echo "$EMAIL_BODY" > email_body.html

      - name: Send deployment checklist email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Replace with your SMTP server
          server_port: 587  # Usually 587 for TLS
          username: ${{ secrets.EMAIL_USERNAME }}  # GitHub secret for email user
          password: ${{ secrets.EMAIL_PASSWORD }}  # GitHub secret for email password
          subject: "Deployment Checklist Summary"
          to: "crownardio@gmail.com"  # Recipient email address
          from: ${{ secrets.EMAIL_USERNAME }}  # Sender email address
          content_type: text/html
          body_file: email_body.html
