name: TTWOS Checklist

on:
  workflow_dispatch:
    inputs:
      verify_changes:
        description: "Verify all code changes are merged into the main branch"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No
      pass_ci_tests:
        description: "Ensure the main branch passes all CI tests"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No
      version_updated:
        description: "Confirm version number is updated if required"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No
      env_variables:
        description: "Update environment variables if needed"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No
      run_workflow:
        description: "Run workflow dispatch from GitHub Actions"
        required: true
        default: "No"
        type: choice
        options:
          - Yes
          - No

jobs:
  deploy-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Deployment Checklist Table
        id: checklist
        run: |
          # Capture inputs as variables
          VERIFY_CHANGES="${{ github.event.inputs.verify_changes }}"
          PASS_CI_TESTS="${{ github.event.inputs.pass_ci_tests }}"
          VERSION_UPDATED="${{ github.event.inputs.version_updated }}"
          ENV_VARIABLES="${{ github.event.inputs.env_variables }}"
          RUN_WORKFLOW="${{ github.event.inputs.run_workflow }}"

          
          # Create the plain text email content
          EMAIL_BODY="Deployment Checklist Summary\n\n"
          EMAIL_BODY+="Step 1: Verify all code changes are merged - $VERIFY_CHANGES\n"
          EMAIL_BODY+="Step 2: Ensure main branch passes all CI tests - $PASS_CI_TESTS\n"
          EMAIL_BODY+="Step 3: Confirm version number is updated if required - $VERSION_UPDATED\n"
          EMAIL_BODY+="Step 4: Update environment variables if needed - $ENV_VARIABLES\n"
          EMAIL_BODY+="Step 5: Run workflow dispatch from GitHub Actions - $RUN_WORKFLOW\n"

          echo "email_body=$EMAIL_BODY" >> $GITHUB_ENV

      - name: Send deployment checklist email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Replace with your SMTP server
          server_port: 587  # Usually 587 for TLS
          username: ${{ secrets.EMAIL_USERNAME }}  # GitHub secret for email user
          password: ${{ secrets.EMAIL_PASSWORD }}  # GitHub secret for email password
          subject: "Deployment Checklist Summary"
          to: "crownardio@gmail.com"  # Recipient email address
          from: ${{ secrets.EMAIL_USERNAME }}  # Sender email address
          content_type: text/html
          body_file: email_body.html
