name: Deployment Checklist

on:
  workflow_dispatch:
    inputs:
      verify_change:
        description: "Verify all code changes are merged into the main branch"
        required: true
        type: choice
        options:
          - Yes
          - No
      pass_ci_tests:
        description: "Ensure the main branch passes all CI tests"
        required: true
        type: choice
        options:
          - Yes
          - No
      version_updated:
        description: "Confirm version number is updated if required"
        required: true
        type: choice
        options:
          - Yes
          - No
      env_variables:
        description: "Update environment variables if needed"
        required: true
        type: choice
        options:
          - Yes
          - No
      run_workflow:
        description: "Run workflow dispatch from GitHub Actions"
        required: true
        type: choice
        options:
          - Yes
          - No

jobs:
  deploy-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Deployment Checklist Table
        id: checklist
        run: |
          # Capture inputs as variables
          VERIFY_CHANGES="${{ github.event.inputs.verify_changes }}"
          PASS_CI_TESTS="${{ github.event.inputs.pass_ci_tests }}"
          VERSION_UPDATED="${{ github.event.inputs.version_updated }}"
          ENV_VARIABLES="${{ github.event.inputs.env_variables }}"
          RUN_WORKFLOW="${{ github.event.inputs.run_workflow }}"

          # Generate a markdown table format for output
          echo "| Step | Description                                        | Completed |" >> checklist.md
          echo "|------|----------------------------------------------------|-----------|" >> checklist.md
          echo "| 1    | Verify all code changes are merged                 | $VERIFY_CHANGES |" >> checklist.md
          echo "| 2    | Ensure main branch passes all CI tests             | $PASS_CI_TESTS |" >> checklist.md
          echo "| 3    | Confirm version number is updated if required      | $VERSION_UPDATED |" >> checklist.md
          echo "| 4    | Update environment variables if needed             | $ENV_VARIABLES |" >> checklist.md
          echo "| 5    | Run workflow dispatch from GitHub Actions          | $RUN_WORKFLOW |" >> checklist.md

          # Output the table to the log
          cat checklist.md

      - name: Display Checklist Output
        run: |
          echo "## Deployment Checklist" >> $GITHUB_STEP_SUMMARY
          cat checklist.md >> $GITHUB_STEP_SUMMARY

      - name: Send deployment checklist email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com  # Replace with your SMTP server
          server_port: 587  # Usually 587 for TLS
          username: ${{ secrets.EMAIL_USERNAME }}  # GitHub secret for email user
          password: ${{ secrets.EMAIL_PASSWORD }}  # GitHub secret for email password
          subject: "Deployment Checklist Summary"
          to: "crownardio@gamil.com"  # Recipient email address
          from: ${{ secrets.EMAIL_USERNAME }}  # Sender email address
          content_type: text/html
          body: |
            <h2>Deployment Checklist Summary</h2>
            <table border="1">
              <tr><th>Step</th><th>Description</th><th>Completed</th></tr>
              <tr><td>1</td><td>Verify all code changes are merged</td><td>${{ github.event.inputs.verify_changes }}</td></tr>
              <tr><td>2</td><td>Ensure main branch passes all CI tests</td><td>${{ github.event.inputs.pass_ci_tests }}</td></tr>
              <tr><td>3</td><td>Confirm version number is updated if required</td><td>${{ github.event.inputs.version_updated }}</td></tr>
              <tr><td>4</td><td>Update environment variables if needed</td><td>${{ github.event.inputs.env_variables }}</td></tr>
              <tr><td>5</td><td>Run workflow dispatch from GitHub Actions</td><td>${{ github.event.inputs.run_workflow }}</td></tr>
            </table>
